### ISSUE TITLE
Generate haddock

### ISSUE THREAD

**Issue by marcosh** [tweag/crem#3]
create a command to generate Haddock documentation.

Make sure that multiline comments + doctests are supported

**Comment by AlexeiDrake** [comment]
The Nix build builds Haddock documentation by default. When the command `nix build` is issued, it creates two directories: `result` and `result-doc`. The structure of `result-doc` looks like this:

```
$ nix build
$ exa --tree result-doc/
result-doc
└── share
   └── doc
      └── crm-0.1.0.0
         └── html
            ├── CRM-BaseMachine.html
            ├── CRM-Graph.html
            ├── CRM-Render.html
            ├── CRM-StateMachine.html
            ├── CRM-Topology.html
            ├── crm.haddock
            ├── crm.txt
            ├── doc-index.html
            ├── doc-index.json
            ├── haddock-bundle.min.js
            ├── index.html
            ├── linuwial.css
            ├── meta.json
            ├── quick-jump.css
            ├── quick-jump.min.js
            ├── src
            │  ├── CRM.BaseMachine.html
            │  ├── CRM.Graph.html
            │  ├── CRM.Render.html
            │  ├── CRM.StateMachine.html
            │  ├── CRM.Topology.html
            │  ├── highlight.js
            │  ├── Paths_crm.html
            │  └── style.css
            └── synopsis.png
```

**Comment by AlexeiDrake** [comment]
We can write a helper to make this generated doc easier to use for the developer, or we can expose it as a CI artefact. What do you think, @marcosh?

**Comment by marcosh** [comment]
If I run `nix-build` locally, I'm not seeing the `result-doc` folder, actually.

For the moment, for me it would be enough to document in the `README.md` where the documentation is created.

Next step (which could be addressed later) would be a command which opens the documentation in a browser

Last step exposing it as a CI artefact (anyway, it would be published on hackage it we decide to put the package there)
