### ISSUE TITLE
hobbit-game: user error (Prelude.readIO: no parse)

### ISSUE THREAD

**Issue by juhp** [tweag/crem#80]
**Describe the bug**
Not sure how to play the hobbit-game

**To Reproduce**
```
$ hobbit-game 
Welcome to the Hobbit adventure game!
You are in a tunnel-like hall.
You can only go east to the Lonelands
go east
hobbit-game: user error (Prelude.readIO: no parse)
```

**Expected behavior**
An error message more helpful that "no parse" would be nice.

Maybe add an example game session output to the Readme?

**Environment**
 - Fedora Linux
 - Version of the code: 0.1.0.0

Perhaps I should try git first?

**Comment by marcosh** [comment]
Hi @juhp thanks for opening the issue! Clearly some documentation is missing.

The parser for the commands is extremely basic. You should use the names for the constructors of the `HobbitCommand` data type (see https://github.com/tweag/crem/blob/962504d35ed146a53b96ddbbe1b531a7cd963f72/examples/Crem/Example/TheHobbit.hs#L21)

**Comment by juhp** [comment]
Thanks!
